/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonApp {
        "name": string;
        "onClick": (event: MouseEvent) => void;
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface ChecktextApp {
        "id": string;
        "name": string;
        "onChange": (event: CustomEvent<HTMLInputElement>) => void;
        "value"?: string;
    }
    interface HeadingApp {
        "description": string;
        "title": string;
    }
    interface InputApp {
        "id": string;
        "label"?: string;
        "onChange": (event: CustomEvent<HTMLInputElement>) => void;
        "placeholder"?: string;
        "type": 'text' | 'number' | 'date' | 'email' | 'password' | 'checkbox';
        "value"?: string;
    }
    interface LinkApp {
        "alt": string;
        "href": string;
        "name": string;
        "src": string;
        "title": string;
    }
}
declare global {
    interface HTMLButtonAppElement extends Components.ButtonApp, HTMLStencilElement {
    }
    var HTMLButtonAppElement: {
        prototype: HTMLButtonAppElement;
        new (): HTMLButtonAppElement;
    };
    interface HTMLChecktextAppElement extends Components.ChecktextApp, HTMLStencilElement {
    }
    var HTMLChecktextAppElement: {
        prototype: HTMLChecktextAppElement;
        new (): HTMLChecktextAppElement;
    };
    interface HTMLHeadingAppElement extends Components.HeadingApp, HTMLStencilElement {
    }
    var HTMLHeadingAppElement: {
        prototype: HTMLHeadingAppElement;
        new (): HTMLHeadingAppElement;
    };
    interface HTMLInputAppElement extends Components.InputApp, HTMLStencilElement {
    }
    var HTMLInputAppElement: {
        prototype: HTMLInputAppElement;
        new (): HTMLInputAppElement;
    };
    interface HTMLLinkAppElement extends Components.LinkApp, HTMLStencilElement {
    }
    var HTMLLinkAppElement: {
        prototype: HTMLLinkAppElement;
        new (): HTMLLinkAppElement;
    };
    interface HTMLElementTagNameMap {
        "button-app": HTMLButtonAppElement;
        "checktext-app": HTMLChecktextAppElement;
        "heading-app": HTMLHeadingAppElement;
        "input-app": HTMLInputAppElement;
        "link-app": HTMLLinkAppElement;
    }
}
declare namespace LocalJSX {
    interface ButtonApp {
        "name"?: string;
        "onClick"?: (event: MouseEvent) => void;
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface ChecktextApp {
        "id"?: string;
        "name"?: string;
        "onChange"?: (event: CustomEvent<HTMLInputElement>) => void;
        "value"?: string;
    }
    interface HeadingApp {
        "description"?: string;
        "title"?: string;
    }
    interface InputApp {
        "id"?: string;
        "label"?: string;
        "onChange"?: (event: CustomEvent<HTMLInputElement>) => void;
        "placeholder"?: string;
        "type"?: 'text' | 'number' | 'date' | 'email' | 'password' | 'checkbox';
        "value"?: string;
    }
    interface LinkApp {
        "alt"?: string;
        "href"?: string;
        "name"?: string;
        "src"?: string;
        "title"?: string;
    }
    interface IntrinsicElements {
        "button-app": ButtonApp;
        "checktext-app": ChecktextApp;
        "heading-app": HeadingApp;
        "input-app": InputApp;
        "link-app": LinkApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-app": LocalJSX.ButtonApp & JSXBase.HTMLAttributes<HTMLButtonAppElement>;
            "checktext-app": LocalJSX.ChecktextApp & JSXBase.HTMLAttributes<HTMLChecktextAppElement>;
            "heading-app": LocalJSX.HeadingApp & JSXBase.HTMLAttributes<HTMLHeadingAppElement>;
            "input-app": LocalJSX.InputApp & JSXBase.HTMLAttributes<HTMLInputAppElement>;
            "link-app": LocalJSX.LinkApp & JSXBase.HTMLAttributes<HTMLLinkAppElement>;
        }
    }
}
